version: '2'

networks:
    bibbox-default-network:
      external: true

services:
  §§INSTANCE-azizi-ona-nginx:
    build:
      context: .
      dockerfile: docker/nginx/nginx_dockerfile
    command: nginx-debug -g 'daemon off;'
    depends_on:
      - §§INSTANCE-azizi-ona-onadata
    links:
      - §§INSTANCE-azizi-ona-onadata:azizi-ona-onadata
    ports:
      - §§PORTWEB:80
    networks:
      - bibbox-default-network

  §§INSTANCE-azizi-ona-db:
    image: kartoza/postgis:9.6-2.4
    container_name: §§INSTANCE-azizi-ona-postgis
    environment:
      - POSTGRES_DB=§§ONA_DATABASE
      - POSTGRES_PASSWORD=§§ONA_PASSWORD
      - POSTGRES_USER=§§ONA_USER
    networks:
      - bibbox-default-network

  §§INSTANCE-azizi-ona-rabbitmq:
    image: gonkulatorlabs/rabbitmq:3.6.1
    networks:
      - bibbox-default-network

  §§INSTANCE-azizi-ona-onadata:
    image: bibbox/azizi-onadata
    command: bash -c "./docker/wait-for-it.sh db:5432 && ./docker/docker-entrypoint.sh"
    environment:
      - PYTHONUNBUFFERED=1
      - DEFAULT_DB_HOST=db
      - DEFAULT_DB_PORT=5432
      - DEFAULT_DB_NAME=§§ONA_DATABASE
      - DEFAULT_DB_USER=§§ONA_USER
      - DEFAULT_DB_PASS=§§ONA_PASSWORD
      - DEV_LOGIN_USERNAME=admin
      - DEV_LOGIN_PASSWORD=onadata
      - MEDIA_URL=http://onadata:8000/media/
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - DJANGO_SETTINGS_MODULE=onadata.settings.docker
      - DEFAULT_DB_ENGINE=django.contrib.gis.db.backends.postgis
    volumes:
      - .:/opt/onadata
    depends_on:
      - §§INSTANCE-azizi-ona-db
      - §§INSTANCE-azizi-ona-rabbitmq
    links:
      - §§INSTANCE-azizi-ona-db
      - §§INSTANCE-azizi-ona-rabbitmq
    networks:
      - bibbox-default-network

  §§INSTANCE-azizi-ona-data:
    image: busybox
    container_name: §§INSTANCE-azizi-ona-data
    networks:
      - bibbox-default-network
    volumes:
      - ./postgres_data:/var/lib/postgresql
      - ./azizi_onadata:/opt/azizi_onadata
