version: '2'

networks:
    bibbox-default-network:
      external: true

services:
  azizi-ona-nginx:
    build:
      context: .
      dockerfile: docker/nginx/nginx_dockerfile
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d:ro
    command: nginx-debug -g 'daemon off;'
    depends_on:
      - azizi-ona-onadata
    links:
      - "azizi-ona-onadata:azizi-ona-onadata"
    ports:
      - 8080:80
    networks:
      - bibbox-default-network

  azizi-ona-db:
    image: kartoza/postgis:9.6-2.4
    container_name: azizi-ona-postgis
    environment:
      - POSTGRES_DB=§§ONA_DATABASE
      - POSTGRES_PASSWORD=§§ONA_PASSWORD
      - POSTGRES_USER=§§ONA_USER
    volumes:
      - .postgres_data/:/var/lib/postgresql:rw
    ports:
      - 5432
    networks:
      - bibbox-default-network

  azizi-ona-rabbitmq:
    image: gonkulatorlabs/rabbitmq:3.6.1
    ports:
      - 15672
      - 5671
      - 5672
    networks:
      - bibbox-default-network

  azizi-ona-onadata:
    image: bibbox/azizi-onadata
    command: bash -c "./docker/wait-for-it.sh db:5432 && ./docker/docker-entrypoint.sh"
    environment:
      - PYTHONUNBUFFERED=1
      - DEFAULT_DB_HOST=db
      - DEFAULT_DB_PORT=5432
      - DEFAULT_DB_NAME=onadata
      - DEFAULT_DB_USER=onadata
      - DEFAULT_DB_PASS=onadata
      - DEV_LOGIN_USERNAME=admin
      - DEV_LOGIN_PASSWORD=onadata
      - MEDIA_URL=http://onadata:8000/media/
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - DJANGO_SETTINGS_MODULE=onadata.settings.docker
      - DEFAULT_DB_ENGINE=django.contrib.gis.db.backends.postgis
    volumes:
      - .:/srv/onadata
    depends_on:
      - azizi-ona-db
      - azizi-ona-rabbitmq
    links:
      - azizi-ona-db
      - azizi-ona-rabbitmq
    ports:
      - 8000
    networks:
      - bibbox-default-network
